<h1><p style="text-align: center;">Data Analysis with Python <br></p><h1> - Traffic Police Stops <img src="https://docs.google.com/uc?id=17CPCwi3_VvzcS87TOsh4_U8eExOhL6Ki" class="img-fluid" alt="CLRSWY" width="200" height="100">

Does the ``gender`` of a driver have an impact on police behavior during a traffic stop? **In this chapter**, you will explore that question while practicing filtering, grouping, method chaining, Boolean math, string methods, and more!

***

## Examining traffic violations

Before comparing the violations being committed by each gender, you should examine the ``violations`` committed by all drivers to get a baseline understanding of the data.

In this exercise, you'll count the unique values in the ``violation`` column, and then separately express those counts as proportions.

> Before starting your work in this section **repeat the steps which you did in the previos chapter for preparing the data.** Continue to this chapter based on where you were in the end of the previous chapter.

In [1]:
import pandas as pd

ri = pd.read_csv("cleaned.csv")
ri.head()

C:\Users\rgize\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,2005-01-02 01:55:00,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,2005-01-02 20:30:00,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,2005-01-04 12:55:00,RI-2005-00004,Zone X4,500,M,1986.0,19.0,W,White,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
3,2005-01-06 01:30:00,RI-2005-00005,Zone X4,500,M,1978.0,27.0,B,Black,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,2005-01-12 08:05:00,RI-2005-00006,Zone X1,0,M,1973.0,32.0,B,Black,Call for Service,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

**INSTRUCTIONS**

*   Count the unique values in the ``violation`` column, to see what violations are being committed by all drivers.
*   Express the violation counts as proportions of the total.

In [2]:
ri['violation'].unique()

array(['Speeding', 'Equipment', 'Other', 'Moving violation',
       'Registration/plates', 'Seat belt'], dtype=object)

In [3]:
ri.violation.value_counts(dropna = False)

Speeding               268736
Moving violation        90228
Equipment               61250
Other                   24216
Registration/plates     19830
Seat belt               16324
Name: violation, dtype: int64

In [4]:
vio_number = ri.violation.value_counts(dropna=False)
df_v = pd.DataFrame(vio_number)
df_v['ratio'] = df_v['violation'] / df_v['violation'].sum() 
df_v

                     violation     ratio
Speeding                268736  0.559186
Moving violation         90228  0.187747
Equipment                61250  0.127449
Other                    24216  0.050389
Registration/plates      19830  0.041262
Seat belt                16324  0.033967

***

## Comparing violations by gender

The question we're trying to answer is whether male and female drivers tend to commit different types of traffic violations.

You'll first create a ``DataFrame`` for each gender, and then analyze the ``violations`` in each ``DataFrame`` separately.

**INSTRUCTIONS**

*   Create a ``DataFrame``, female, that only contains rows in which ``driver_gender`` is ``'F'``.
*   Create a ``DataFrame``, male, that only contains rows in which ``driver_gender`` is ``'M'``.
*   Count the ``violations`` committed by female drivers and express them as proportions.
*   Count the violations committed by male drivers and express them as proportions.

In [5]:
ri["driver_gender"].value_counts(dropna = False)

M    349446
F    131138
Name: driver_gender, dtype: int64

In [6]:
female = ri[ri.driver_gender == "F"]

male = ri[ri.driver_gender == "M"]

In [7]:
female.head()

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
14,2005-02-24 01:20:00,RI-2005-00016,Zone X3,200,F,1983.0,22.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
16,2005-03-14 10:00:00,RI-2005-00019,Zone K3,300,F,1984.0,21.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
23,2005-03-29 23:20:00,RI-2005-00026,Zone K3,300,F,1971.0,34.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
32,2005-06-06 13:20:00,RI-2005-00035,Zone X4,500,F,1986.0,19.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
33,2005-06-18 16:30:00,RI-2005-00037,Zone X4,500,F,1964.0,41.0,W,White,Other Traffic Violation,...,False,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4

In [8]:
male.head()

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,2005-01-02 01:55:00,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,2005-01-02 20:30:00,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,2005-01-04 12:55:00,RI-2005-00004,Zone X4,500,M,1986.0,19.0,W,White,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
3,2005-01-06 01:30:00,RI-2005-00005,Zone X4,500,M,1978.0,27.0,B,Black,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,2005-01-12 08:05:00,RI-2005-00006,Zone X1,0,M,1973.0,32.0,B,Black,Call for Service,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

In [9]:
female.violation.value_counts(normalize = True)

Speeding               0.657308
Moving violation       0.136581
Equipment              0.107055
Registration/plates    0.043077
Other                  0.028908
Seat belt              0.027071
Name: violation, dtype: float64

In [10]:
male.violation.value_counts(normalize = True)

Speeding               0.522364
Moving violation       0.206948
Equipment              0.135102
Other                  0.058450
Registration/plates    0.040581
Seat belt              0.036555
Name: violation, dtype: float64

2nd Way;

     ri_female_num=female['violation'].value_counts(dropna = False)
     ri_female_num = pd.DataFrame(ri_female_num)
     ri_male_num=male['violation'].value_counts(dropna = False)
     ri_male_num = pd.DataFrame(ri_male_num)
     ri_female_num['ratio']=ri_female_num/ri_female_num.sum()
     ri_female_num

     ri_male_num['ratio']=ri_male_num/ri_male_num.sum()
     ri_male_num

In [11]:
ri.groupby(["driver_gender"])["violation"].value_counts(normalize = True, dropna = False)

driver_gender  violation
F              Speeding               0.657308
               Moving violation       0.136581
               Equipment              0.107055
               Registration/plates    0.043077
               Other                  0.028908
               Seat belt              0.027071
M              Speeding               0.522364
               Moving violation       0.206948
               Equipment              0.135102
               Other                  0.058450
               Registration/plates    0.040581
               Seat belt              0.036555
Name: violation, dtype: float64

***

## Comparing speeding outcomes by gender

When a driver is pulled over for speeding, many people believe that gender has an impact on whether the driver will receive a ticket or a warning. Can you find evidence of this in the dataset?

First, you'll create two ``DataFrames`` of drivers who were stopped for ``speeding``: one containing ***females*** and the other containing ***males***.

Then, for each **gender**, you'll use the ``stop_outcome`` column to calculate what percentage of stops resulted in a ``"Citation"`` (meaning a ticket) versus a ``"Warning"``.

**INSTRUCTIONS**

*   Create a ``DataFrame``, ``female_and_speeding``, that only includes female drivers who were stopped for speeding.
*   Create a ``DataFrame``, ``male_and_speeding``, that only includes male drivers who were stopped for speeding.
*   Count the **stop outcomes** for the female drivers and express them as proportions.
*   Count the **stop outcomes** for the male drivers and express them as proportions.

In [12]:
female_and_speeding = ri[(ri.driver_gender == "F") & (ri.violation == "Speeding")]

male_and_speeding = ri[(ri.driver_gender == "M") & (ri.violation == "Speeding")]

In [13]:
female_and_speeding.head()

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
14,2005-02-24 01:20:00,RI-2005-00016,Zone X3,200,F,1983.0,22.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
16,2005-03-14 10:00:00,RI-2005-00019,Zone K3,300,F,1984.0,21.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
23,2005-03-29 23:20:00,RI-2005-00026,Zone K3,300,F,1971.0,34.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
32,2005-06-06 13:20:00,RI-2005-00035,Zone X4,500,F,1986.0,19.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
34,2005-07-06 11:22:00,RI-2005-00038,Zone X1,0,F,1973.0,32.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X1

In [14]:
male_and_speeding.head()

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,2005-01-02 01:55:00,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,2005-01-02 20:30:00,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
5,2005-01-18 08:15:00,RI-2005-00007,Zone K3,300,M,1965.0,40.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
7,2005-01-23 23:15:00,RI-2005-00009,Zone K3,300,M,1972.0,33.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
8,2005-01-24 20:32:00,RI-2005-00010,Zone K1,600,M,1987.0,18.0,W,White,Speeding,...,True,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1

In [15]:
ri.stop_outcome.value_counts()

Citation            428378
Warning              28840
Arrest Driver        14630
N/D                   3431
No Action             3332
Arrest Passenger      1973
Name: stop_outcome, dtype: int64

In [16]:
male_and_speeding.stop_outcome.value_counts(normalize = True)

Citation            0.944636
Warning             0.036086
Arrest Driver       0.015767
Arrest Passenger    0.001265
N/D                 0.001183
No Action           0.001063
Name: stop_outcome, dtype: float64

In [17]:
female_and_speeding.stop_outcome.value_counts(normalize = True)

Citation            0.953247
Warning             0.039003
Arrest Driver       0.005290
Arrest Passenger    0.001033
N/D                 0.000905
No Action           0.000522
Name: stop_outcome, dtype: float64

In [18]:
pd.options.display.max_rows = 500

In [19]:
#ri.groupby(["violation","driver_gender"])["stop_outcome"].value_counts(normalize = True)
ri.groupby(["driver_gender","violation"])["stop_outcome"].value_counts(normalize = True)

driver_gender  violation            stop_outcome
F              Equipment            Citation            0.727830
                                    Warning             0.157490
                                    N/D                 0.047938
                                    Arrest Driver       0.040387
                                    Arrest Passenger    0.021227
                                    No Action           0.005129
               Moving violation     Citation            0.839149
                                    Warning             0.099045
                                    Arrest Driver       0.043939
                                    Arrest Passenger    0.010441
                                    No Action           0.004857
                                    N/D                 0.002568
               Other                Citation            0.639409
                                    No Action           0.212873
                                    Arrest Driver       0.111580
                                    Warning             0.019520
                                    N/D                 0.012925
                                    Arrest Passenger    0.003693
               Registration/plates  Citation            0.861037
                                    Arrest Driver       0.070278
                                    Warning             0.052753
                                    Arrest Passenger    0.008320
                                    No Action           0.004426
                                    N/D                 0.003186
               Seat belt            Citation            0.836901
                                    Warning             0.139437
                                    Arrest Driver       0.013803
                                    Arrest Passenger    0.008169
                                    No Action           0.001690
               Speeding             Citation            0.953247
                                    Warning             0.039003
                                    Arrest Driver       0.005290
                                    Arrest Passenger    0.001033
                                    N/D                 0.000905
                                    No Action           0.000522
M              Equipment            Citation            0.760818
                                    Warning             0.131368
                                    Arrest Driver       0.049268
                                    N/D                 0.041918
                                    Arrest Passenger    0.010760
                                    No Action           0.005867
               Moving violation     Citation            0.861416
                                    Warning             0.073731
                                    Arrest Driver       0.052961
                                    Arrest Passenger    0.005047
                                    No Action           0.004702
                                    N/D                 0.002143
               Other                Citation            0.842742
                                    Arrest Driver       0.071922
                                    No Action           0.065606
                                    Warning             0.012093
                                    N/D                 0.005875
                                    Arrest Passenger    0.001763
               Registration/plates  Citation            0.852267
                                    Arrest Driver       0.082223
                                    Warning             0.045624
                                    No Action           0.006981
                                    Arrest Passenger    0.006558
                                    N/D                 0.006347
               Seat belt            Citation            0.842179
                                    Warning             0.126116
                                    Arrest Driver       0.022076
                                    Arrest Passenger    0.005950
                                    No Action           0.003131
                                    N/D                 0.000548
               Speeding             Citation            0.944636
                                    Warning             0.036086
                                    Arrest Driver       0.015767
                                    Arrest Passenger    0.001265
                                    N/D                 0.001183
                                    No Action           0.001063
Name: stop_outcome, dtype: float64

***

## Calculating the search rate

During a traffic stop, the police officer sometimes conducts a search of the vehicle. In this exercise, you'll calculate the percentage of all stops that result in a vehicle search, also known as the **search rate**.

**INSTRUCTIONS**

*   Check the data type of ``search_conducted`` to confirm that it's a ``Boolean Series``.
*   Calculate the search rate by counting the ``Series`` values and expressing them as proportions.
*   Calculate the search rate by taking the mean of the ``Series``. (It should match the proportion of ``True`` values calculated above.)

In [20]:
print(ri.search_conducted.dtype)

bool

In [21]:
ri.search_conducted.value_counts()

False    462822
True      17762
Name: search_conducted, dtype: int64

In [22]:
#round(ri.search_conducted.mean(),6)
ri.search_conducted.mean() # TRUE / Total length of dataframe

0.036959199640437465

***

## Comparing search rates by gender

You'll compare the rates at which **female** and **male** drivers are searched during a traffic stop. Remember that the vehicle search rate across all stops is about **3.8%**.

First, you'll filter the ``DataFrame`` by gender and calculate the search rate for each group separately. Then, you'll perform the same calculation for both genders at once using a ``.groupby()``.

**INSTRUCTIONS 1/3**

*   Filter the ``DataFrame`` to only include **female** drivers, and then calculate the search rate by taking the mean of ``search_conducted``.

In [23]:
ri[ri.driver_gender == "F"].search_conducted.mean() # TRUE / F SUM

0.018751239152648355

**INSTRUCTIONS 2/3**

*   Filter the ``DataFrame`` to only include **male** drivers, and then repeat the search rate calculation.

In [24]:
ri[ri.driver_gender == "M"].search_conducted.mean()  # TRUE / M SUM

0.04379217389811301

**INSTRUCTIONS 3/3**

*   Group by driver gender to calculate the search rate for both groups simultaneously. (It should match the previous results.)

In [25]:
ri.groupby(["driver_gender"])["search_conducted"].mean()

driver_gender
F    0.018751
M    0.043792
Name: search_conducted, dtype: float64

***

## Adding a second factor to the analysis

Even though the search rate for males is much higher than for females, it's possible that the difference is mostly due to a second factor.

For example, you might hypothesize that the search rate varies by violation type, and the difference in search rate between males and females is because they tend to commit different violations.

You can test this hypothesis by examining the search rate for each combination of gender and violation. If the hypothesis was true, you would find that males and females are searched at about the same rate for each violation. Find out below if that's the case!

**INSTRUCTIONS 1/2**

*   Use a ``.groupby()`` to calculate the search rate for each combination of gender and violation. Are males and females searched at about the same rate for each violation?

In [26]:
ri.groupby(["driver_gender","violation"]).search_conducted.mean()

driver_gender  violation
F              Equipment              0.040245
               Moving violation       0.038021
               Other                  0.045898
               Registration/plates    0.054700
               Seat belt              0.017746
               Speeding               0.007738
M              Equipment              0.070916
               Moving violation       0.059156
               Other                  0.046120
               Registration/plates    0.103589
               Seat belt              0.031705
               Speeding               0.026630
Name: search_conducted, dtype: float64

**INSTRUCTIONS 2/2**

*   Reverse the ordering to group by violation before gender. The results may be easier to compare when presented this way.

In [27]:
ri.groupby(["violation","driver_gender"]).search_conducted.mean()

violation            driver_gender
Equipment            F                0.040245
                     M                0.070916
Moving violation     F                0.038021
                     M                0.059156
Other                F                0.045898
                     M                0.046120
Registration/plates  F                0.054700
                     M                0.103589
Seat belt            F                0.017746
                     M                0.031705
Speeding             F                0.007738
                     M                0.026630
Name: search_conducted, dtype: float64

***

## Counting protective frisks

During a vehicle search, the police officer may pat down the driver to check if they have a weapon. This is known as a ``"protective frisk."``

You'll first check to see how many times "Protective Frisk" was the only search type. Then, you'll use a string method to locate all instances in which the driver was frisked.

**INSTRUCTIONS**

*   Count the ``search_type`` values to see how many times ``"Protective Frisk"`` was the only search type.
*   Create a new column, frisk, that is ``True`` if ``search_type`` contains the string ``"Protective Frisk"`` and ``False`` otherwise.
*   Check the data type of frisk to confirm that it's a ``Boolean Series``.
*   Take the sum of frisk to count the total number of frisks.

In [28]:
ri.search_type.value_counts()

Incident to Arrest                                          6998
Probable Cause                                              4989
Reasonable Suspicion                                        1141
Inventory                                                   1101
Protective Frisk                                             879
Incident to Arrest,Inventory                                 649
Incident to Arrest,Probable Cause                            552
Probable Cause,Reasonable Suspicion                          334
Probable Cause,Protective Frisk                              221
Incident to Arrest,Protective Frisk                          158
Incident to Arrest,Inventory,Probable Cause                  151
Inventory,Probable Cause                                     132
Protective Frisk,Reasonable Suspicion                         83
Incident to Arrest,Inventory,Protective Frisk                 77
Incident to Arrest,Probable Cause,Protective Frisk            74
Inventory,Protective Frisk                                    52
Incident to Arrest,Reasonable Suspicion                       49
Incident to Arrest,Probable Cause,Reasonable Suspicion        31
Probable Cause,Protective Frisk,Reasonable Suspicion          31
Inventory,Reasonable Suspicion                                17
Inventory,Probable Cause,Protective Frisk                     14
Incident to Arrest,Inventory,Reasonable Suspicion             12
Incident to Arrest,Protective Frisk,Reasonable Suspicion       8
Inventory,Probable Cause,Reasonable Suspicion                  8
Inventory,Protective Frisk,Reasonable Suspicion                1
Name: search_type, dtype: int64

In [29]:
#Try the wrong way and see why it is wrong? len(ri[ri['search_type']=='Protective Frisk'])
ri["frisk"] = ri.search_type.str.contains("Protective Frisk", na = False)

In [30]:
ri.frisk.dtype

dtype('bool')

In [31]:
ri.frisk.sum()

1598

In [32]:
ri.frisk

0         False
1         False
2         False
3         False
4         False
          ...
480579    False
480580    False
480581    False
480582    False
480583    False
Name: frisk, Length: 480584, dtype: bool

In [33]:
ri[ri.frisk]

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
9,2005-02-09 03:05:00,RI-2005-00011,Zone X4,500,M,1976.0,29.0,W,White,Registration Violation,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4,True
77,2005-08-28 01:00:00,RI-2005-00084,Zone X1,0,M,1979.0,26.0,W,White,Other Traffic Violation,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,16-30 Min,True,False,Zone X1,True
236,2005-10-01 16:20:00,RI-2005-00253,Zone K1,600,M,1958.0,47.0,W,White,Speeding,...,"Reasonable Suspicion,Terry Frisk","Protective Frisk,Reasonable Suspicion",True,Citation,False,16-30 Min,False,False,Zone K1,True
997,2005-10-06 21:35:00,RI-2005-01027,Zone X4,500,M,1966.0,39.0,W,White,Speeding,...,Terry Frisk,Protective Frisk,False,Citation,False,0-15 Min,False,False,Zone X4,True
1088,2005-10-07 11:33:00,RI-2005-01121,Zone X4,900,M,1980.0,25.0,W,White,Equipment/Inspection Violation,...,Terry Frisk,Protective Frisk,False,Arrest Driver,True,16-30 Min,False,False,Zone X4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477084,2015-11-27 19:49:00,RI-2015-43442,Zone X3,200,M,1986.0,29.0,W,White,Speeding,...,Terry Frisk,Protective Frisk,False,Warning,False,0-15 Min,True,False,Zone X3,True
478052,2015-12-06 10:33:00,RI-2015-44434,Zone K3,300,M,1993.0,22.0,L,Hispanic,Speeding,...,Terry Frisk,Protective Frisk,True,Citation,False,16-30 Min,True,True,Zone K3,True
478696,2015-12-12 09:02:00,RI-2015-45103,Zone X4,500,M,1982.0,33.0,W,White,Other Traffic Violation,...,Terry Frisk,Protective Frisk,False,Citation,False,16-30 Min,True,False,Zone X4,True
479078,2015-12-16 02:38:00,RI-2015-45507,Zone K3,200,M,1988.0,27.0,L,Hispanic,Speeding,...,"Incident to Arrest,Odor of Drugs/Alcohol,Terry...","Incident to Arrest,Probable Cause,Protective F...",True,Arrest Driver,True,30+ Min,False,True,Zone K3,True
480394,2015-12-30 01:37:00,RI-2015-46870,Zone X4,500,M,1979.0,36.0,W,White,Registration Violation,...,Terry Frisk,Protective Frisk,False,Citation,False,0-15 Min,False,False,Zone X4,True

***

## Comparing frisk rates by gender

You'll compare the rates at which female and male drivers are frisked during a search. Are males frisked more often than females, perhaps because police officers consider them to be higher risk?

Before doing any calculations, it's important to filter the ``DataFrame`` to only include the relevant subset of data, namely stops in which a search was conducted.

**INSTRUCTIONS**

*   Create a ``DataFrame``, searched, that only contains rows in which ``search_conducted`` is ``True``.
*   Take the mean of the frisk column to find out what percentage of searches included a frisk.
*   Calculate the frisk rate for each gender using a ``.groupby()``.

In [34]:
pd.options.display.max_columns = 500

In [35]:
searched = ri[ri.search_conducted]

searched

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,violation,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
8,2005-01-24 20:32:00,RI-2005-00010,Zone K1,600,M,1987.0,18.0,W,White,Speeding,Speeding,True,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1,False
9,2005-02-09 03:05:00,RI-2005-00011,Zone X4,500,M,1976.0,29.0,W,White,Registration Violation,Registration/plates,True,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4,True
77,2005-08-28 01:00:00,RI-2005-00084,Zone X1,0,M,1979.0,26.0,W,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,16-30 Min,True,False,Zone X1,True
83,2005-09-15 02:20:00,RI-2005-00094,Zone X4,500,M,1988.0,17.0,W,White,Other Traffic Violation,Moving violation,True,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone X4,False
104,2005-09-24 02:20:00,RI-2005-00115,Zone K3,300,M,1987.0,18.0,W,White,Other Traffic Violation,Moving violation,True,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone K3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480234,2015-12-28 11:05:00,RI-2015-46706,Zone K3,300,F,1996.0,19.0,W,White,APB,Other,True,Incident to Arrest,Incident to Arrest,True,Citation,False,16-30 Min,True,True,Zone K3,False
480394,2015-12-30 01:37:00,RI-2015-46870,Zone X4,500,M,1979.0,36.0,W,White,Registration Violation,Registration/plates,True,Terry Frisk,Protective Frisk,False,Citation,False,0-15 Min,False,False,Zone X4,True
480427,2015-12-30 08:51:00,RI-2015-46903,Zone K3,300,F,1987.0,28.0,H,Hispanic,Speeding,Speeding,True,"Probable Cause,Reasonable Suspicion","Probable Cause,Reasonable Suspicion",True,Citation,False,30+ Min,True,True,Zone K3,False
480458,2015-12-30 13:15:00,RI-2015-46934,Zone X3,200,M,1992.0,23.0,W,White,Seatbelt Violation,Seat belt,True,Incident to Arrest,Incident to Arrest,False,Arrest Passenger,True,16-30 Min,True,False,Zone X3,False
480473,2015-12-30 15:58:00,RI-2015-46950,Zone K2,900,M,1976.0,39.0,W,White,Other Traffic Violation,Moving violation,True,"Odor of Drugs/Alcohol,Probable Cause,Reasonabl...","Probable Cause,Reasonable Suspicion",False,Citation,False,30+ Min,True,False,Zone K2,False

In [36]:
searched.frisk.mean()

0.08996734601959239

In [37]:
searched.groupby("driver_gender").frisk.mean()

driver_gender
F    0.066694
M    0.093707
Name: frisk, dtype: float64